// flow-typed signature: b222c3e3afd84ea28adf8e0e62343d18
// flow-typed version: <<STUB>>/@mdi/font_v^5.9.55/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdi/font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdi/font' {
  declare module.exports: any;
}
