// flow-typed signature: 78b02ce5b859bbf5bd6c9eb004df6b28
// flow-typed version: <<STUB>>/uglifycss_v^0.0.29/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifycss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifycss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglifycss/uglifycss-lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglifycss/index' {
  declare module.exports: $Exports<'uglifycss'>;
}
declare module 'uglifycss/index.js' {
  declare module.exports: $Exports<'uglifycss'>;
}
declare module 'uglifycss/uglifycss-lib.js' {
  declare module.exports: $Exports<'uglifycss/uglifycss-lib'>;
}
